#pragma once
#include "CoreMinimal.h"
#include "EChallengeName.generated.h"

UENUM(BlueprintType)
enum class EChallengeName : uint8 {
    None,
    SaveYourAmmo,
    UpCloseAndPersonal,
    DownButNotOut,
    CantKeepMyEyesOffOfYou,
    DeadManWalking,
    BetterTheEnemyYouKnow,
    PickOnSomeoneYourOwnSize,
    GetYourHandsDirty,
    CrowdControl,
    DefendThisHouse,
    ThereGoesTheNeighborhood,
    FamilyMatters,
    InterceptedSignal,
    BlackFriday,
    UpInSmoke,
    BuriedAlive,
    DoNoHarm,
    FightTheMan,
    MisterPresident,
    AloneOrAlive,
    TeamWork,
    NeighborhoodWatch,
    OverkillingIt,
    ShortAndSweet,
    RiseAndShine,
    CantTouchThis,
    FeelingCrafty,
    ICanDoThisAllDay,
    PieceByPiece,
    Resourceful,
    GoodSamaritan,
    TheBestOffense,
    WelcomeToMyHome,
    TeamPlayer,
    ItTakesAVillage,
    CampCouncelor,
    GunsBlazing,
    Jam,
    CaughtRedHanded,
    Homecoming,
    DontTouchMyStuff,
    IllTakeThat,
    Scrapper,
    BringItOn,
    FixerUpper,
    HoardAgainstTheHorde,
    IRememberYou,
    OldDogMeetNewTricks,
    RepeatAfterMe,
    GearUp,
    Amen,
    StayAWhileAndListen,
    YesSanctuary,
    NoSmoking,
    FueledUp,
    BlackGold,
    Wholesome,
    SignLanguage,
    GroceryGuns,
};

